version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: web-server
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - main

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    image: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wp-data:/var/www/html
    networks:
      - main

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main

#        ---------- VOLUMES -----------
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH}
      o: bind
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WP_PATH}
      o: bind

#         ---------- NETWORKS -----------
networks:
  main:
    name: main
    driver: bridge
