
services:
  nginx:
    containers
    build: requirements/nginx
    image: web-server
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
  
  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    image: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb
    image: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception

volumes:
  db-data:
  wp-data:
networks:
  inception:
